spring:
  application:
    name: spring-app-json-logging
  output:
    ansi:
      enabled: always
  profiles:
    active: local
    include: json

management:
  endpoint:
    health:
      show-details: always